# Change these first
owner: GeorgeDong32 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Light Server
    url: $LIGHT_SERVER
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/server.svg
    check: "tcp-ping"
    expectedStatusCodes:
      - 200
      - 201
      - 304
    __dangerous__insecure: true
  - name: Server-T1
    url: $ROOT_SERVER
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/server.svg
    expectedStatusCodes:
      - 200
      - 201
      - 304
    __dangerous__insecure: true
  - name: Bitwarden
    url: $BITWARDEN_SITE
    icon: https://vault.bitwarden.com/images/favicon-32x32.png
  - name: Image Storage 1
    url: $STORAGE1_SITE
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/storage.svg
  - name: Blog
    url: https://blog.georgedong.tech
  - name: Home Page
    url: https://www.georgedong.tech
  - name: GoodPass Site
    url: https://goodpass.georgedong.tech
  - name: Alist
    url: $SHARE_SITE
    icon: https://cdn.jsdelivr.net/gh/alist-org/logo@main/logo.svg
  - name: Status Page
    url: https://status.georgedong.tech
  - name: Shortlink Service
    url: https://go.georgedong.tech
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/link.svg
  - name: Pandora Next
    url: $PANDORA_SITE
    icon: https://uptime.georgedong.tech/icons/pandoranext.ico
  - name: Gemini Chat
    url: $GEMINI_SITE
    icon: https://uptime.georgedong.tech/icons/Gemini.png
  - name: Emergency Plan
    url: $EMERGENCY_PLAN_SITE
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/plan.svg
  - name: Tailscale
    url: $TAILSCALE
    icon: https://tailscale.com/files/favicon.ico
  - name: Upptime Heartbeat
    url: https://uptime.betterstack.com/api/v1/heartbeat/$HEARTBEAT_ID
    icon: https://uptime.georgedong.tech/icons/betterstack.png
assignees:
  - GeorgeDong32
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.georgedong.tech
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/GeorgeDong32/upptime/master/assets/favicon.ico
  favicon: https://raw.githubusercontent.com/GeorgeDong32/upptime/master/assets/favicon.ico
  name: Uptime | GeorgeDong.tech
  introTitle: "**georgedong.tech上的网站状态**"
  introMessage: 这是一个完全由Github驱动的网站状态监测系统 — 基于Github Action, Issue和Github Page, [**由upptime驱动**](https://github.com/upptime/upptime)
  navbar:
    - title: Uptime
      href: /
    - title: Status
      href: https://status.georgedong.tech
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"
  links:
    - rel: stylesheet
      href: https://uptime.georgedong.tech/CSS/mylight.css
      media: "(prefers-color-scheme: light)"
    - rel: stylesheet
      href: https://uptime.georgedong.tech/CSS/mydark.css
      media: "(prefers-color-scheme: dark)"

user-agent: GeorgeDong32

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: 活动事件
  allSystemsOperational: 所有服务均正常运行
  incidentReport: "事件 #$NUMBER 报告 →"
  activeIncidentSummary: 发生于 $DATE ，共有 $POSTS 个提交
  incidentTitle: 事件 $NUMBER 的详细信息
  incidentDetails: 事件详细信息
  incidentFixed: 已修复
  incidentOngoing: 正在进行
  incidentOpenedAt: 开始于
  incidentClosedAt: 结束于
  incidentSubscribe: 订阅事件
  incidentViewOnGitHub: 在 GitHub 上查看
  incidentCommentSummary: 由 $AUTHOR 在 $DATE 发布
  incidentBack: ← 返回主页
  pastIncidents: 过去的事件
  pastIncidentsResolved: $POSTS 个问题在 $MINUTES 分钟内得到解决
  liveStatus: 实时状态
  overallUptime: "总计正常运行时间： $UPTIME"
  overallUptimeTitle: 总计正常运行时间
  averageResponseTime: "平均响应时间: $TIMEms"
  averageResponseTimeTitle: 平均响应时间
  sevelDayResponseTime: 近 7 天平均响应时间
  responseTimeMs: 响应时间（ms）
  loading: 加载中
  navGitHub: GitHub
  footer: Copyright © 2023 GeorgeDong32. All Rights Reserved. 由 GeorgeDong32 与 Upptime 和 Github 共同构建。
  rateLimitExceededTitle: 超出速率限制
  rateLimitExceededIntro: 您已超过一小时内可以执行的请求数，因此您必须等待才能再次访问此网站。或者您可以添加 GitHub 个人访问令牌以继续使用本网站。
  rateLimitExceededWhatDoesErrorMean: 这个错误是什么意思？本网站使用 GitHub API 访问有关我们网站状态的实时数据。默认情况下，GitHub 允许每个 IP 地址每小时 60 发送个请求，您已经超出了这个请求限额。
  rateLimitExceededErrorHowCanFix: 我该如何解决？
  rateLimitExceededErrorFix: 您可以等待一个小时，直到针对您的 IP 地址的限制被解除。或者您可以添加您的 GitHub 个人访问令牌，这将为您提供每小时额外 5,000 个请求。
  rateLimitExceededGeneratePAT: 了解如何生成个人访问令牌
  rateLimitExceededHasSet: 您有一个个人访问令牌集。
  rateLimitExceededRemoveToken: 删除令牌
  rateLimitExceededGitHubPAT: GitHub 个人访问令牌
  rateLimitExceededCopyPastePAT: 复制并粘贴您的令牌
  rateLimitExceededSaveToken: 保存令牌
  errorTitle: 发生错误
  errorIntro: 尝试获取最新状态详细信息时出错。
  errorText: 您可以稍后再试。
  errorHome: 转到主页
  pastScheduledMaintenance: 过去的计划维护
  scheduledMaintenance: 计划中的维护
  scheduledMaintenanceSummaryStarted: 从 $DATE 开始，持续 $DURATION 分钟
  scheduledMaintenanceSummaryStarts: 从 $DATE 开始，持续 $DURATION 分钟
  startedAt: 开始于
  startsAt: 开始于
  duration: 持续时间
  durationMin: $DURATION 分钟
  incidentCompleted: 已完成
  incidentScheduled: 已预定
  url: "网站"
  status: "状态"
  history: "历史信息"
  responseTime: "响应时间"
  uptime: "正常运行时间"
  up: "🟩 正常运行"
  degraded: "🟨 运行缓慢"
  down: "🟥 停机"
  responseTimeGraphAlt: "响应时间图像"
  responseTimeDay: "24小时平均响应时间"
  responseTimeWeek: "7天平均响应时间"
  responseTimeMonth: "30天平均响应时间"
  responseTimeYear: "1年平均响应时间"
  uptimeDay: "24小时正常运行时间"
  uptimeWeek: "7天正常运行时间"
  uptimeMonth: "30天正常运行时间"
  uptimeYear: "1年正常运行时间"
  liveStatusHtmlComment: "<！ -实时状态- >"
  degradedPerformance: "🟨 运行缓慢"
  completeOutage: "🟥 所有服务均宕机"
  partialOutage: "🟧 部分服务宕机"
