# Change these first
owner: GeorgeDong32 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Bitwarden Service
    url: $BITWARDEN_SITE
  - name: Image Storage 1
    url: $STORAGE1_SITE
  - name: Root
    check: "tcp-ping"
    url: $ROOT_SERVER
  - name: Blog
    url: https://blog.georgedong.tech
  - name: Home Page
    url: https://www.georgedong.tech
  - name: GoodPass Site
    url: https://goodpass.georgedong.tech
  - name: Shortlink Service
    url: $SHORTLINK_SITE
  - name: Emergency Plan
    url: $EMERGENCY_PLAN_SITE
  - name: Tailscale
    url: $TAILSCALE
  - name: Status Page by upptime
    url: https://uptime.georgedong.tech
  - name: Status Page on Better Stack
    url: $STATUS_PAGE

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.georgedong.tech
  # baseUrl: /your-repo-name
  logoUrl: https://uptime.georgedong.tech/image.jpg
  name: Upptime | GeorgeDong32
  introTitle: "**Uptime of website on georgedong.tech**"
  introMessage: Upptime is the open-source uptime monitor and status page, powered entirely by GitHub. No server required — just GitHub Actions, Issues, and Pages. [**Driven by upptime**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: GeorgeDong32

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
