# Change these first
owner: GeorgeDong32 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Bitwarden Service
    url: $BITWARDEN_SITE
    icon: https://vault.bitwarden.com/images/favicon-32x32.png
  - name: Image Storage 1
    url: $STORAGE1_SITE
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/storage.svg
  - name: Light Server
    url: $LIGHT_SERVER
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/server.svg
    check: "tcp-ping"
    expectedStatusCodes:
      - 200
      - 201
      - 304
    __dangerous__insecure: true
  - name: Root
    url: $ROOT_SERVER
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/server.svg
    expectedStatusCodes:
      - 200
      - 201
      - 304
    __dangerous__insecure: true
  - name: Blog
    url: https://blog.georgedong.tech
  - name: Home Page
    url: https://www.georgedong.tech
  - name: GoodPass Site
    url: https://goodpass.georgedong.tech
  - name: Share Site
    url: $SHARE_SITE
  - name: Shortlink Service
    url: https://go.georgedong.tech
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/link.svg
  - name: Emergency Plan
    url: $EMERGENCY_PLAN_SITE
    icon: https://raw.githubusercontent.com/GeorgeDong32/Public-Resources/main/site-icon/plan.svg
  - name: Tailscale
    url: $TAILSCALE
    icon: https://tailscale.com/files/favicon.ico
  - name: Status Page by upptime
    url: https://upptime.georgedong.tech
assignees:
  - GeorgeDong32
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.georgedong.tech
  # baseUrl: /your-repo-name
  logoUrl: https://upptime.georgedong.tech/image.jpg
  name: Upptime | GeorgeDong32
  introTitle: "**Uptime of website on georgedong.tech**"
  introMessage: Upptime is the open-source uptime monitor and status page, powered entirely by GitHub. No server required — just GitHub Actions, Issues, and Pages. [**Driven by upptime**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

user-agent: GeorgeDong32

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
